language: python
services:
  - docker
  - mongodb
  - rabbitmq
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      before_install:
        - docker --version;
        - docker-compose --version;
        - pip install --user codecov
    - os: osx
      sudo: required
      language: generic
      before_install:
        - brew update
        - virtualenv env -p python
        - source env/bin/activate
        - brew install mongodb
        - sudo mkdir -p /data/db
        - brew services start mongodb
        - pip install --user codecov
env:
  - TRAVIS_NODE_VERSION="8.9.0"
after_success:
  - codecov
install:
  # Clear out whatever version of NVM Travis has.
  # Grab NVM and checkout the latest stable tag.
  # Install the desired version of Node
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm install
  - python --version
  - npm run pip-install
script:
  - npm run cibuild
  - npm run pylint
  - npm run pytests
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run docker-build; fi
