language: python
services:
  - docker
  - mongodb
  - rabbitmq
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
      before_install:
        - docker --version;
        - docker-compose --version;
    - os: osx
      sudo: required
      language: generic
      addons:
        homebrew:
          #update: true
          packages: python3
      before_install:
        - python3 -m pip install --upgrade virtualenv
        - virtualenv -p python3 --system-site-packages "$HOME/venv"
        - source "$HOME/venv/bin/activate"
        #- brew update
        #- python -m pip install --upgrade virtualenv
        #- virtualenv env -p python
        #- source env/bin/activate
        #- brew uninstall mongodb
        - brew cask reinstall mongodb
        - sudo mkdir -p /data/db
        - brew services start mongodb
        - which mongo
        - which mongod
env:
  - TRAVIS_NODE_VERSION="8.9.0"
after_success:
  - npm run codecov
install:
  # Clear out whatever version of NVM Travis has.
  # Grab NVM and checkout the latest stable tag.
  # Install the desired version of Node
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm install
  - python --version
  - npm run pip-install
script:
  - npm run cibuild
  - npm run pylint
  - npm run pytests
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run docker-build; fi
