sudo: required
language: node_js
services:
  - docker
os:
  - linux
  - osx
node_js:
  - "6"
before_install:
  - node --version
  - npm --version
  - docker --version
  - docker-compose --version
script:
  - npm run cibuild
  - npm run docker-build
