#sudo: required
language: python
services:
  - docker
  - mongodb
  - rabbitmq
matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      sudo: required
      language: generic
      before_install:
        - brew update
        - brew install python
        - virtualenv env -p python
        - source env/bin/activate
#os:
#  - linux
#  - osx
#python:
#  - 2.7
env:
  - TRAVIS_NODE_VERSION="8.4.0"
before_install:
  # Clear out whatever version of NVM Travis has.
  # Grab NVM and checkout the latest stable tag.
  # Install the desired version of Node
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm --version
  - npm install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker --version;
    docker-compose --version;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo "Installing and starting mongodb";
    brew install mongodb;
    sudo mkdir -p /data/db;
    brew services start mongodb;
    fi
  - python --version
  - npm run pip-install
script:
  - npm run cibuild
  - npm run pylint
  - npm run pytests
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run docker-build; fi
