sudo: required
language: node_js
services:
  - docker
  - mongodb
os:
  - linux
  - osx
node_js:
  - "6"
python:
  - "2.7"
before_install:
  - node --version
  - npm --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    docker --version;
    docker-compose --version;
    sudo apt-get install python
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    echo "Updating homebrew";
    brew update;
    echo "Installing and starting mongodb";
    brew install mongodb;
    sudo mkdir -p /data/db;
    brew services start mongodb;
    echo "Installing python";
    brew install python;
    fi
  - python --version
  - npm run pip-install
script:
  - npm run cibuild
  - npm run pylint
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run docker-build; fi
