version: "2"
services:
  web:
    container_name: draaljs
    build:
      context: .
      dockerfile: ./config/app/Dockerfile-prod
    expose:
      - "3008"
    env_file:
     - .env-docker-aws
    environment:
      - PORT=3008
    volumes:
      - web:/draaljs-app
  aws_nginx:
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile-aws
    links:
      - web
    volumes_from:
      - web
volumes:
  web:
