version: "2"
services:
  aws:
    container_name: draaljs
    build:
      context: .
      dockerfile: ./config/app/Dockerfile-prod
    expose:
      - "3008"
    env_file:
     - .env-docker-aws
    environment:
      - PORT=3008
