version: "2"
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./config/rabbitmq
      dockerfile: Dockerfile
    ports:
      - "5672:5672"
  mongodb:
    container_name: mongodb
    image: mongo:3.6
  web:
    container_name: draaljs
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3008"
    volumes:
      - .:/draaljs-app
      - /draaljs-app/node_modules
      - docker-logs:/var/log
    env_file:
     - .env-docker
    environment:
      - PORT=3008
    depends_on:
      - mongodb
      - rabbitmq
      - worker
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - "8088:80"
    links:
      - web
    volumes_from:
      - web
  worker:
    build:
      context: .
      dockerfile: ./config/celery/Dockerfile
    volumes:
      - .:/draaltasks
      - docker-logs:/var/log
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    env_file:
     - .env-docker
volumes:
  docker-logs:
    driver_opts:
      device: ${PWD}/docker-logs
      o: bind
