version: "2"
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.4
  web:
    container_name: draaljs
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3008"
    volumes:
      - .:/draaljs-app
      - /draaljs-app/node_modules
    environment:
      - PORT=3008
      - MONGODB_URI=mongodb://mongodb:27017/test
      - ACCOUNT_ACTIVATION_DAYS=7
    depends_on:
      - mongodb
  nginx:
    container_name: nginx
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    ports:
      - "8008:80"
    links:
      - web
    volumes_from:
      - web
