FROM rabbitmq

# https://stackoverflow.com/questions/30747469/how-to-add-initial-users-when-starting-a-rabbitmq-docker-container
# https://groups.google.com/forum/#!topic/rabbitmq-users/vfNSfSkP3uw
CMD ["rabbitmqctl", "add_vhost", "draal_tasks"]
#CMD ["rabbitmqctl", "add_vhost", "draal_tasks"]
