name: CI Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.8]
        os: [ubuntu-latest]

    services:
      mongodb:
        image: mongo:3.4.23
        ports:
          - 27017:27017

      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672
        # Needed because the rabbitmq container does not provide a healthcheck
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare node-gyp for ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install g++ build-essential ffmpeg

      - name: npm install, build, and test
        run: |
          npm i
          which python
          which pip
          python --version
          pip --version
          npm run pip-install
          npm run cibuild
          npm run pylint
          npm run pytests
        env:
          CI: true

      - name: Docker build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: npm run docker-build
