name: CI Build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x]
        python-version: [3.8]
        mongodb-version: [3.6]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - uses: nijel/rabbitmq-action@v1.0.0
        with:
          rabbitmq version: '5'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Prepare node-gyp for ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install g++ build-essential

      - name: npm install, build, and test
        run: |
          npm i
          which python
          which pip
          python --version
          pip --version
          npm run pip-install
          npm run cibuild
          npm run pylint
          npm run pytests
        env:
          CI: true
